server:
  port: 8010
spring:
  application:
    name: microservice-simple-consumer-movie-trace
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 192.168.189.129
    port: 5672
    username: test
    password: test  
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG