server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xyl1204/config-repo.git
          username: xyl891204@126.com
          password: XueYunLong1912