server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  rabbitmq:
    host: 192.168.189.129
    port: 5672
    username: test
    password: test
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin1234@localhost:8761/eureka/