server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin1234@localhost:8761/eureka/
  healthcheck:
    enabled: true
microservice-provider-user:
  ribbon:
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule