server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xyl1204/config-repo.git
          username: 
          password: 
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
