server:
  port: 8080
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xyl1204/config-repo.git
          username: 
          password:
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin1234@localhost:8761/eureka/
