server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin1234@localhost:8761/eureka/
  healthcheck:
    enabled: true
logging:
  level:
    com.xyl.microservice.client.UserFeignClient: DEBUG