server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xyl1204/config-repo.git
          username: 
          password: 
encrypt:
  key-store:
    location: classpath:server.jks
    password: letmein
    alias: mytestkey
    secret: changeme
