server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xyl1204/config-repo.git
          username: 
          password: 
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.189.129
    port: 5672
    username: test
    password: test
        
